platform :ios, '9.0'

flutter_application_path = '../flutter_integrate_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'SwiftFlutterIntegrateApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  install_all_flutter_pods(flutter_application_path)

  # Pods for SwiftFlutterIntegrateApp

  target 'SwiftFlutterIntegrateAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftFlutterIntegrateAppUITests' do
    # Pods for testing
  end

end