platform :ios, '9.0'

flutter_application_path = '../flutter_integrate_module'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'SwiftFlutterIntegrateApp' do
  pod 'AFNetworking', '~> 3.0'
  pod 'FBSDKCoreKit', '~> 4.9'
  install_all_flutter_pods(flutter_application_path)
end